"""empty message

Revision ID: 3aed9545ca54
Revises: 976a4a68d2b6
Create Date: 2019-12-26 20:34:39.195677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aed9545ca54'
down_revision = '976a4a68d2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('gtype', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'gtype')
    # ### end Alembic commands ###
